### ISSUE TITLE
drag a piece of text or image?

### ISSUE THREAD

**Issue by tommyvct** [sireliah/dragit#1]
like this
![image](https://user-images.githubusercontent.com/7903172/103202714-ccacef80-48b8-11eb-9c09-b531ace519d6.png)

**Comment by sireliah** [comment]
Dragging text and images to the application context is absolutely possible, however what should happen on the receiver end? When you drag text (let's say, from a browser) to Nautilus, the text file with dragged text will be created. Would you like this kind of behaviour on the target machine? Or maybe do you have better idea?

**Comment by tommyvct** [comment]
I prefer the implementation in Samsung flow, just like the picture above. 
It's like a chat interface, there should be a text box that you can put any text you want on both ends.

I actually did [a similar thing](https://github.com/tommyvct/zeroconftransfer) of this before, but it's written in Python and command line only. That was for my distributed systems class term project. I used a different header when sending texts.

**Comment by nmendozam** [comment]
Maybe if the text is too long it could show it as a file, with the name been the first line or something, such that it does not take too much space.

**Comment by sireliah** [comment]
@nmendozam That makes sense. Now I think I have idea how to present transferred goods (files/text/images).

- Under each device, show list (history) of transferred objects. List would be collapsible.
- Files: show title (and allow clicking on the file to open the directory or the file itself)
- Text: show first n lines of the text as title.
- Images: show thumbnail

**Comment by sireliah** [comment]
I'm designing a bit improved UI now. For sending bare text or image I'll need to make some changes to the protocol, but the skeleton for the UI will look like that:

![dragit_recent](https://user-images.githubusercontent.com/17201781/104518005-4f42e800-55f7-11eb-95b8-d33059bd01ce.png)

**Comment by sireliah** [comment]
Hi! You can check the new release: https://github.com/sireliah/dragit/releases/tag/v0.4.0

I've added dragging text and the history of the files. It's pretty rudimentary now, but should work.

The Windows version doesn't support dragging text (can only receive text payloads), because of the different API for the drag & drop. I might research it later if people think it's useful to have this feature.
