### ISSUE TITLE
Crash on startup under Windows 10

### ISSUE THREAD

**Issue by graphixillusion** [sireliah/dragit#17]
Hi there. As the title says i'm getting this error upon start under Windows 10 version 21H1 build 19043.1237

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-09-15T19:28:43.6349259Z" /> 
  <EventRecordID>28837</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>MEFISTO-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>dragit.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>610e714c</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.1202</Data> 
  <Data>c9db1934</Data> 
  <Data>80000003</Data> 
  <Data>00000000000c9b92</Data> 
  <Data>228c</Data> 
  <Data>01d7aa67e3ef7318</Data> 
  <Data>D:\PortableAppz\dragit\dragit.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>42d7ca7c-d4c6-4fe7-b6e4-b4e6a2002902</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by sireliah** [comment]
Hi! Thanks for reporting the problem. As far as I tested, sometimes anti-virus software block gdbus.exe and this causes dragit to exit. Could you please check if this is not an issue (that is, do you get any new notifications regarding blocked programs)?

**Comment by sireliah** [comment]
Another thing that comes to my mind are the potentially missing VC runtime libs that are required to run the program. Please check this: https://github.com/sireliah/dragit#windows-requirements

**Comment by graphixillusion** [comment]
@sireliah The system already have VC runtime installed: i've tried to update to the last version but nothing, still the same error. I'm using Windows Defender as AV and it seems that it doesn't block anything: by the way i've also tried to disable it and run the program again, still the same issue.

**Comment by sireliah** [comment]
@graphixillusion I've just noticed that the error report you've attached contains path `D:\PortableAppz\dragit\dragit.exe`. The current Windows release of dragit (built by CI/CD) has following structure:
```
├── bin
│   ├── atk-1.0-0.dll
│   ├── cairo.dll
│   ├── cairo-gobject.dll
│   ├── dragit.exe
 |      (...) lots of other dlls
├── lib
│   └── gdk-pixbuf-2.0
└── share
```

How do you run the app? Did you build the Windows version yourself or you're running the latest release? If this is latest release, the binary should be in the same path as the dlls. Could you please check that?

**Comment by graphixillusion** [comment]
@sireliah Yep, you are right, i was using the version from the release page but instead of keeping the whole folder structure, i keeped just the bin folder and deleted the other two. With all the folders in place, it starts without problems: i was believing that only the bin folder was needed to make it runs. Thanks again for the support!
