### ISSUE TITLE
Needs a better logo icon for small sizes and contrast issues?

### ISSUE THREAD

**Issue by nekohayo** [sireliah/dragit#30]
I understand the funny visual metaphor with the current logo icon, but it has a few usability problems

* It's full of tiny details (cables, struts, etc.) that get lost visually at sizes below 48x48 because they are too fine
* Colors don't really match GNOME or Tango palette styles
* Colors don't have any contrast against a dark background (such as the GNOME Shell apps grid, dash, or using extensions like dash-to-panel. You cannot see the black cables/struts against a black/dark background, and even the turquoise-deep-blue machinery is very low-contrast against that background.

Overall, the current visual metaphor is lost when the icon is displayed in most/all UI elements as an app launcher.

**Comment by sireliah** [comment]
Hi! Thanks for the hints. The reason is that I didn't really follow GNOME icon guidelines when I designed the icon. I think that the idea of simplifying the icon and changing the color palette is pretty good. I.e. like [these icons](https://developer.gnome.org/hig/_images/app-icons.svg). 

If you don't mind, I'll prepare the new version of the icon and ask you for review.

**Comment by nekohayo** [comment]
Thanks for being open to this :) I have no particular idea/suggestion of what it _should_ be instead, but I think a big part of the underlying cause of the issues you may face is that—beyond the color issues—the heavy machinery thing with tension cables is difficult to represent at small sizes. Also, there were things that were not helping the metaphor, such as the  big cogwheel ("what does the cogwheel have to do with dragging?"). I mean, a catapult, slingshot or crane would be clearer if you want to retain the machinery imagery; but in terms of computing, dragging from one computer to another has little to do with heavy machinery 🤔

**Comment by sireliah** [comment]
@nekohayo check if the contrast is better in this version: [PR](https://github.com/sireliah/dragit/pull/41/files)
